name: Testing CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Builder
        if: github.event_name == 'push'
        run: |
          echo test
          export NAME="$(git log -1 --format=%s)"
          export TAG="$(git log -1 --format=%b)"
          
          if [ $NAME = "b" ]
          then
            echo "Run Builder Deploy"
            echo CommitName:
            echo $NAME
            echo CommitTag:
            echo $TAG
            if [ ! -d "releases/" ]; then
              mkdir releases
            fi
            zip -r $TAG.zip . -x ".git/*" ".github/*"
            mv $TAG.zip releases/
            git config --global user.email "yurilima95@gmail.com"
            git config --global user.name "yuri-almeid"
            git add .
            git commit -m "📦 - Actions: Building"
            git push
            
          else
            echo "Not building..."
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      - name: run that commit
        if: github.event.head_commit.message == 'asd'
        run: |
          echo test

      - name: run a pull request
        if: github.event_name == 'pull_request'
        run: |
          echo just a just a pull request
          ls

