name: Testing CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Builder
        if: github.event_name == 'push'
        run: |
          echo test
          export NAME="$(git log -1 --format=%s)"
          export TAG="$(git log -1 --format=%b)"
          
          if [ $NAME = "build" ]
          then
            echo "Run Builder Deploy"
            echo CommitName:
            echo $NAME
            echo CommitTag:
            echo $TAG
            zip -r releases/$TAG.zip main.py
            ls
            ls relaeses/
          else
            echo "Not building..."
          fi
       
      - name: run that commit
        if: github.event.head_commit.message == 'asd'
        run: |
          echo test


      
      - name: run a pull request
        if: github.event_name == 'pull_request'
        run: |
          echo just a just a pull request
          ls

