name: Testing CI

on:
  push:
    branches: [ prod, main ]
  pull_request:
    branches: [ prod, main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Builder
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        run: |
          
          echo test
          export NAME="$(git log -1 --format=%s)"
          export TAG="$(git log -1 --format=%b)"          
          git branch
          
          if [ $NAME = "b" ]
          then
            echo "Inicia Builder"
            echo Nome:
            echo $NAME
            echo Tag:
            echo $TAG
            
            if [ ! -d "releases/" ]; then
              mkdir releases
            fi
            echo Criando pacote
            zip -r $TAG.zip . -x ".git/*" ".github/*" "releases/"
            mv $TAG.zip releases/
            echo Atualizando github
            git config --global user.email "yurilima95@gmail.com"
            git config --global user.name "yuri-almeid"
            # git add .
            # git commit -m "📦 - Actions: Building"
            # git push
            echo Dando merge no main
            
            
          else
            echo "Not building..."
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      - name: run that commit
        if: github.event.head_commit.message == 'asd'
        run: |
          echo test

      - name: run a pull request
        if: github.event_name == 'pull_request'
        run: |
          echo just a just a pull request
          ls

