name: Testing CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: run a push
        if: github.event_name == 'push'
        run: |
          echo just a push
      
      - name: run that commit
        if: github.event.head_commit.message == 'asd'
        run: |
          echo test
          echo $T
          echo $ST
        env:
          T: git log -1 --format=%s
          ST: git log -1 --format=%b


      
      - name: run a pull request
        if: github.event_name == 'pull_request'
        run: |
          echo just a just a pull request
          ls

