name: Testing CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: run a push
        if: github.event_name == 'push'
        run: |
          echo just a push
          echo ${{ github.event.head_commit.message }}
          echo github.event.commits[][message]
          echo github.event.commits[0][message]
      
      - name: run that commit
        if: github.event.head_commit.message == 'asd'
        run: |


      
      - name: run a pull request
        if: github.event_name == 'pull_request'
        run: |
          echo just a just a pull request
          ls

